### PR TITLE
 Change Bottom Bar Selected Color ……..

### PR DESCRIPTION
**Pull request by Harsh-raj-x07**

### CODE REVIEW

**Comment by Harsh-raj-x07** [comment]
Hey @MohitGupta121  r u there ? Pls merge ………this is my first contribution 🙃

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
What are you doing? Fix it 
I'll Mark it as spam.

**Comment by MohitGupta121** [comment]
@Harsh0326 are you fixing this or I'll close this?

**Comment by Harsh-raj-x07** [comment]
> @Harsh0326 are you fixing this or I'll close this?

Ok

**Comment by MohitGupta121** [comment]
@Harsh0326 okay fix it.

**Comment by MohitGupta121** [comment]
#21 is now fixed in PR #25 so no need for this PR

**Pull request closed without merging**
