### PR TITLE
Implement Team Fragment using Compose

### PR DESCRIPTION
**Pull request by Harsh-raj-x07**
Thanks  !

## Essential Checklist

- [ ] The PR title and explanation each start with "Fix #bugnum: " (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)

## For UI-specific PRs only

If your PR includes UI-related changes, then:
- Add screenshots of the before & after UI changes

### CODE REVIEW

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
What is this?
Make ui using compose I mark this spam.

**Comment by Harsh-raj-x07** [comment]
> What is this?
> Make ui using compose I mark this spam.

Code …..you can run ? And get …….colour changes in bottom layouts

**Comment by MohitGupta121** [comment]
@Harsh0326 Add Team Fragment using compose, Already working on this issue

**Comment by MohitGupta121** [comment]
> > What is this?
> > Make ui using compose I mark this spam.
> 
> Code …..you can run ? And get …….colour changes in bottom layouts

Use proper compose method to do that, no need to add new file.

**Comment by Harsh-raj-x07** [comment]
> > > What is this?
> > > Make ui using compose I mark this spam.
> > 
> > 
> > Code …..you can run ? And get …….colour changes in bottom layouts
> 
> Use proper compose method to do that, no need to add new file.

Screenshot se  ? Chlega 😭

**Comment by MohitGupta121** [comment]
No man, stop it

**Pull request closed without merging**
